"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { FileText, Scale, ArrowRight } from "lucide-react";

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.06, duration: 0.5, ease: [0.25, 0.46, 0.45, 0.94] },
  }),
};

const SECTIONS = [
  { num: "01", title: "Acceptance of Terms", body: "By accessing or using GitRating (\"the Service\"), operated by Mozen (\"we\", \"us\", \"our\"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service." },
  { num: "02", title: "Description of Service", body: "GitRating analyzes publicly available GitHub data to generate an engineering credibility score and shareable report. The Service is provided \"as is\" and may be modified or discontinued at any time." },
  { num: "03", title: "Account and Authentication", body: "You may authenticate via GitHub OAuth. We request read-only access to your public GitHub profile and repositories. We do not store your OAuth token. You are responsible for your GitHub account security." },
  { num: "04", title: "Your Data", body: "You retain full ownership of your GitHub data. We access only what is necessary to generate your score, and you may delete your account and all data at any time. We do not sell or share your data with third parties." },
  { num: "05", title: "Scoring and Analysis", body: "Scores are generated by AI models analyzing publicly available GitHub metadata. Scores are not guaranteed to be accurate, complete, or reflective of your actual engineering ability. They are directional signals, not definitive assessments." },
  { num: "06", title: "Acceptable Use", body: "You agree not to: (a) misuse the Service to harass, defame, or harm others; (b) attempt to circumvent rate limits or security; (c) use the Service for illegal purposes; (d) reverse-engineer our scoring methodology." },
  { num: "07", title: "Intellectual Property", body: "The Service, including its design, code, and AI models, is the intellectual property of Mozen. You may not copy, modify, or distribute any part without written permission." },
  { num: "08", title: "Limitation of Liability", body: "To the maximum extent permitted by law, Mozen and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service." },
  { num: "09", title: "Changes to Terms", body: "We may update these terms at any time. Continued use after changes constitutes acceptance. Material changes will be communicated via email or a notice on the Service." },
  { num: "10", title: "Governing Law", body: "These terms are governed by the laws of India. Disputes shall be resolved in the courts of Tamil Nadu, India." },
  { num: "11", title: "Contact", body: "Questions about these terms? Email us at legal@mozen.in." },
];

const MARQUEE = ["TERMS", "PRIVACY", "SECURITY", "LEGAL", "COMPLIANCE", "TRANSPARENCY"];

export default function TermsPage() {
  return (
    <main style={{ overflow: "hidden" }}>
      {/* Hero */}
      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: "-20%", right: "15%", width: "400px", height: "400px", borderRadius: "50%", backgroundColor: "var(--accent)", opacity: 0.07, filter: "blur(80px)", pointerEvents: "none" }} />
        <div style={{ maxWidth: "1100px", margin: "0 auto", padding: "clamp(2.5rem, 6vw, 5rem) 1.5rem", position: "relative", display: "grid", gridTemplateColumns: "1fr auto", gap: "2rem", alignItems: "start" }} className="terms-hero">
          <div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.12em", color: "var(--accent)", marginBottom: "1rem", display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <FileText size={14} />
              Legal
            </motion.div>
            <motion.h1 initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.1 }} style={{ fontFamily: "var(--font-display)", fontSize: "clamp(2.2rem, 5vw, 3.8rem)", fontWeight: 700, lineHeight: 1.05, letterSpacing: "-0.04em", margin: 0 }}>
              Terms of{" "}
              <span style={{ color: "var(--accent)" }}>Service</span>
            </motion.h1>
            <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }} style={{ fontFamily: "var(--font-mono)", fontSize: "0.78rem", color: "var(--muted)", marginTop: "0.75rem" }}>
              Last updated: July 2026
            </motion.p>
          </div>
          <motion.div initial={{ opacity: 0, scale: 0.8, rotate: -8 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ duration: 0.7, delay: 0.2 }} className="terms-icon" style={{ width: "7rem", height: "7rem", border: "var(--border-width) solid var(--ink)", borderRadius: "var(--radius)", boxShadow: "var(--shadow-lg)", backgroundColor: "var(--paper-alt)", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <Scale size={40} style={{ color: "var(--ink)" }} />
          </motion.div>
        </div>
      </div>

      {/* Marquee */}
      <div style={{ backgroundColor: "var(--ink)", borderTop: "var(--border-width) solid var(--ink)", borderBottom: "var(--border-width) solid var(--ink)", overflow: "hidden", whiteSpace: "nowrap", padding: "0.55rem 0" }}>
        <div style={{ display: "inline-flex", animation: "marquee 18s linear infinite" }}>
          {[...MARQUEE, ...MARQUEE].map((item, i) => (
            <span key={i} style={{ fontFamily: "var(--font-display)", fontSize: "0.65rem", fontWeight: 700, letterSpacing: "0.15em", color: "var(--paper)", padding: "0 1.75rem", display: "inline-flex", alignItems: "center", gap: "1.25rem" }}>
              {item}
              <span style={{ width: 3, height: 3, backgroundColor: "var(--accent)", borderRadius: "50%", flexShrink: 0 }} />
            </span>
          ))}
        </div>
        <style>{`@keyframes marquee { from { transform: translateX(0); } to { transform: translateX(-50%); } } @media (prefers-reduced-motion: reduce) { @keyframes marquee { from, to { transform: translateX(0); } } }`}</style>
      </div>

      {/* Content */}
      <div style={{ maxWidth: "1100px", margin: "0 auto", padding: "clamp(2rem, 5vw, 4rem) 1.5rem" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: "0" }}>
          {SECTIONS.map((s, i) => (
            <motion.div key={s.num} custom={i} initial="hidden" animate="show" variants={fadeUp} style={{ display: "grid", gridTemplateColumns: "auto 1fr", borderBottom: "var(--border-width) solid var(--ink)" }}>
              <div style={{ padding: "1.5rem 1.5rem 1.5rem 0", borderRight: "var(--border-width) solid var(--ink)", marginRight: "1.5rem", minWidth: "3.5rem", display: "flex", flexDirection: "column", alignItems: "center" }}>
                <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "1.1rem", color: "var(--accent)", lineHeight: 1 }}>{s.num}</div>
              </div>
              <div style={{ padding: "1.5rem 0" }}>
                <h2 style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "1.05rem", marginBottom: "0.5rem" }}>{s.title}</h2>
                <p style={{ fontFamily: "var(--font-body)", fontSize: "0.88rem", lineHeight: 1.75, color: "var(--muted)" }}>{s.body}</p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* CTA */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5, duration: 0.5 }} style={{ marginTop: "3rem", textAlign: "center", padding: "2rem 0 1rem" }}>
          <Link href="/" className="btn-primary">Get your Engineering Score <ArrowRight size={15} /></Link>
        </motion.div>
      </div>

      <style>{`@media (max-width: 768px) { .terms-hero { grid-template-columns: 1fr !important; } .terms-icon { display: none !important; } }`}</style>
    </main>
  );
}
